# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayPayCurrency' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayPayCurrency

  pod 'Alamofire'

  target 'PayPayCurrencyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PayPayCurrencyUITests' do
    # Pods for testing
  end

end
